// <auto-generated />
using System;
using Cleanuparr.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cleanuparr.Persistence.Migrations.Events
{
    [DbContext(typeof(EventsContext))]
    [Migration("20261003180000_AddUsenetEvents")]
    partial class AddUsenetEvents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.UsenetObservation", b =>
            {
                b.Property<string>("Id").IsRequired().HasColumnType("TEXT").HasColumnName("id");
                b.Property<Guid>("ClientId").HasColumnType("TEXT").HasColumnName("client_id");
                b.Property<Guid>("OwnerId").HasColumnType("TEXT").HasColumnName("owner_id");
                b.Property<long>("LastSeenTicks").HasColumnType("INTEGER").HasColumnName("last_seen_ticks");
                b.Property<long>("UnchangedSinceTicks").HasColumnType("INTEGER").HasColumnName("unchanged_since_ticks");
                b.Property<int>("Samples").HasColumnType("INTEGER").HasColumnName("samples");
                b.Property<string>("Fingerprint").IsRequired().HasColumnType("TEXT").HasColumnName("fingerprint");
                b.Property<string>("Progress").IsRequired().HasColumnType("TEXT").HasColumnName("progress");
                b.Property<string>("Incident").IsRequired().HasColumnType("TEXT").HasColumnName("incident");
                b.Property<string>("ActionState").IsRequired().HasColumnType("TEXT").HasColumnName("action_state");
                b.Property<long>("ActionTicks").HasColumnType("INTEGER").HasColumnName("action_ticks");
                b.Property<string>("RecoveryProgress").IsRequired().HasColumnType("TEXT").HasColumnName("recovery_progress");
                b.HasKey("Id").HasName("pk_usenet_observations");
                b.ToTable("usenet_observations");
            });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Events.AppEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<string>("CleanReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("clean_reason");

                    b.Property<string>("CleanedCategory")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("cleaned_category");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CycleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cycle_id");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("delete_reason");

                    b.Property<Guid?>("DownloadClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.PrimitiveCollection<string>("FailedImportReasons")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("failed_import_reasons");

                    b.PrimitiveCollection<string>("GrabbedItems")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("grabbed_items");

                    b.Property<bool?>("IsCategoryTag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_category_tag");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_dry_run");

                    b.Property<string>("ItemHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_hash");

                    b.Property<string>("ItemTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_title");

                    b.Property<Guid?>("JobRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_run_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("NewCategory")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("new_category");

                    b.Property<string>("OldCategory")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("old_category");

                    b.Property<bool?>("RemoveFromClient")
                        .HasColumnType("INTEGER")
                        .HasColumnName("remove_from_client");

                    b.Property<string>("SearchReason")
                        .HasColumnType("TEXT")
                        .HasColumnName("search_reason");

                    b.Property<string>("SearchStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("search_status");

                    b.Property<string>("SearchType")
                        .HasColumnType("TEXT")
                        .HasColumnName("search_type");

                    b.Property<double?>("SeedRatio")
                        .HasColumnType("REAL")
                        .HasColumnName("seed_ratio");

                    b.Property<double?>("SeedingTimeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("seeding_time_hours");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<int?>("StrikeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("strike_count");

                    b.Property<Guid?>("StrikeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("strike_id");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<Guid?>("TrackingId")
                        .HasColumnType("TEXT")
                        .HasColumnName("tracking_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("ArrInstanceId")
                        .HasDatabaseName("ix_events_arr_instance_id");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("ix_events_cycle_id");

                    b.HasIndex("DeleteReason")
                        .HasDatabaseName("ix_events_delete_reason");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_events_event_type");

                    b.HasIndex("JobRunId")
                        .HasDatabaseName("ix_events_job_run_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_events_severity");

                    b.HasIndex("StrikeId")
                        .HasDatabaseName("ix_events_strike_id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_events_timestamp");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Events.ManualEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DownloadClientName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_name");

                    b.Property<string>("DownloadClientType")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_client_type");

                    b.Property<string>("InstanceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_type");

                    b.Property<string>("InstanceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("instance_url");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_dry_run");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_resolved");

                    b.Property<string>("ItemHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_hash");

                    b.Property<string>("ItemTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_title");

                    b.Property<Guid?>("JobRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_run_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<string>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<int?>("StrikeCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("strike_count");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_manual_events");

                    b.HasIndex("InstanceType")
                        .HasDatabaseName("ix_manual_events_instance_type");

                    b.HasIndex("IsResolved")
                        .HasDatabaseName("ix_manual_events_is_resolved");

                    b.HasIndex("JobRunId")
                        .HasDatabaseName("ix_manual_events_job_run_id");

                    b.HasIndex("Message")
                        .HasDatabaseName("ix_manual_events_message");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_manual_events_severity");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("ix_manual_events_timestamp");

                    b.HasIndex("Type", "ItemHash")
                        .IsUnique()
                        .HasDatabaseName("ix_manual_events_type_item_hash")
                        .HasFilter("\"is_resolved\" = 0");

                    b.ToTable("manual_events", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.CustomFormatScoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_score");

                    b.Property<int>("CutoffScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cutoff_score");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<long>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsMonitored")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_monitored");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<string>("LastSyncedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("LastUpgradedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_upgraded_at");

                    b.Property<string>("QualityProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("quality_profile_name");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_custom_format_score_entries");

                    b.HasIndex("LastUpgradedAt")
                        .HasDatabaseName("ix_custom_format_score_entries_last_upgraded_at");

                    b.HasIndex("ArrInstanceId", "ExternalItemId", "EpisodeId")
                        .IsUnique()
                        .HasDatabaseName("ix_custom_format_score_entries_arr_instance_id_external_item_id_episode_id");

                    b.ToTable("custom_format_score_entries", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.CustomFormatScoreHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<int>("CutoffScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cutoff_score");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<string>("RecordedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_custom_format_score_history");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_custom_format_score_history_recorded_at");

                    b.HasIndex("ArrInstanceId", "ExternalItemId", "EpisodeId")
                        .HasDatabaseName("ix_custom_format_score_history_arr_instance_id_external_item_id_episode_id");

                    b.ToTable("custom_format_score_history", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.DownloadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DownloadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("download_id");

                    b.Property<bool>("IsMarkedForRemoval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_marked_for_removal");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_removed");

                    b.Property<bool>("IsReturning")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_returning");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_download_items");

                    b.HasIndex("DownloadId")
                        .IsUnique()
                        .HasDatabaseName("ix_download_items_download_id");

                    b.ToTable("download_items", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_job_runs");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_job_runs_started_at");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_job_runs_type");

                    b.ToTable("job_runs", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SearchQueueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("ItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_id");

                    b.Property<string>("SearchType")
                        .HasColumnType("TEXT")
                        .HasColumnName("search_type");

                    b.Property<long?>("SeriesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_search_queue");

                    b.HasIndex("ArrInstanceId")
                        .HasDatabaseName("ix_search_queue_arr_instance_id");

                    b.ToTable("search_queue", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SeekerCommandTracker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<long>("CommandId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("command_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("episode_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_title");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seeker_command_trackers");

                    b.HasIndex("ArrInstanceId")
                        .HasDatabaseName("ix_seeker_command_trackers_arr_instance_id");

                    b.ToTable("seeker_command_trackers", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.SeekerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("ArrInstanceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("arr_instance_id");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cycle_id");

                    b.Property<long>("ExternalItemId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("external_item_id");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_dry_run");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_title");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("item_type");

                    b.Property<string>("LastSearchedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_searched_at");

                    b.Property<int>("SearchCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("search_count");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("season_number");

                    b.HasKey("Id")
                        .HasName("pk_seeker_history");

                    b.HasIndex("ArrInstanceId", "ExternalItemId", "ItemType", "SeasonNumber", "CycleId")
                        .IsUnique()
                        .HasDatabaseName("ix_seeker_history_arr_instance_id_external_item_id_item_type_season_number_cycle_id");

                    b.ToTable("seeker_history", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.Strike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DownloadItemId")
                        .HasColumnType("TEXT")
                        .HasColumnName("download_item_id");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_dry_run");

                    b.Property<Guid>("JobRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("job_run_id");

                    b.Property<long?>("LastDownloadedBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_downloaded_bytes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_strikes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_strikes_created_at");

                    b.HasIndex("JobRunId")
                        .HasDatabaseName("ix_strikes_job_run_id");

                    b.HasIndex("DownloadItemId", "Type")
                        .HasDatabaseName("ix_strikes_download_item_id_type");

                    b.ToTable("strikes", (string)null);
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Events.AppEvent", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.State.JobRun", "JobRun")
                        .WithMany("Events")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_events_job_runs_job_run_id");

                    b.HasOne("Cleanuparr.Persistence.Models.State.Strike", "Strike")
                        .WithMany()
                        .HasForeignKey("StrikeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_events_strikes_strike_id");

                    b.Navigation("JobRun");

                    b.Navigation("Strike");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.Events.ManualEvent", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.State.JobRun", "JobRun")
                        .WithMany("ManualEvents")
                        .HasForeignKey("JobRunId")
                        .HasConstraintName("fk_manual_events_job_runs_job_run_id");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.Strike", b =>
                {
                    b.HasOne("Cleanuparr.Persistence.Models.State.DownloadItem", "DownloadItem")
                        .WithMany("Strikes")
                        .HasForeignKey("DownloadItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_strikes_download_items_download_item_id");

                    b.HasOne("Cleanuparr.Persistence.Models.State.JobRun", "JobRun")
                        .WithMany("Strikes")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_strikes_job_runs_job_run_id");

                    b.Navigation("DownloadItem");

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.DownloadItem", b =>
                {
                    b.Navigation("Strikes");
                });

            modelBuilder.Entity("Cleanuparr.Persistence.Models.State.JobRun", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("ManualEvents");

                    b.Navigation("Strikes");
                });
#pragma warning restore 612, 618
        }
    }
}
